name: 'Reviewer lottery - with labels'
description: 'Automatically assign reviewers to Pull Requests. This is an extension of Reviewer lottery with an added feature: triggering groups by label matching.'
author: 'Unai Esteibar and Gabriel Melo'
branding:
  icon: 'eye'
  color: 'orange'
inputs:
  repo-token:
    description: "Github token secret"
    required: true
  config:
    description: 'Path to config file'
    default: '.github/reviewer-lottery.yml'
runs:
  using: 'node16'
  main: 'dist/index.js'
